version: '2'
services:
  java-app:
    image: testcase/library:0.1
    container_name: library-app
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - postgres-db
    command: ["./wait-for-it.sh", "postgres-db:5432", "--", "python", "app.py"]

  postgres-db:
    image: kiasaki/alpine-postgres:latest
    container_name: library-db
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres